# Generated by Django 3.2.11 on 2022-10-05 14:30

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tag name')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(max_length=120, verbose_name='Venue')),
                ('venue_address', models.CharField(max_length=120)),
                ('venue_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_image', models.ImageField(blank=True, upload_to='', verbose_name='Image')),
                ('student_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('student_linkedin', models.URLField(blank=True, verbose_name='Linkedin URL')),
                ('student_tag', models.ManyToManyField(related_name='student_tag', to='events.Tag')),
                ('student_user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=100, verbose_name='Title')),
                ('event_started', models.TimeField(verbose_name='Start')),
                ('event_ended', models.TimeField(blank=True, null=True, verbose_name='End')),
                ('event_date', models.DateField(verbose_name='Date')),
                ('event_description', ckeditor.fields.RichTextField()),
                ('event_website', models.URLField(blank=True, max_length=100, null=True, verbose_name='URL')),
                ('event_email', models.EmailField(max_length=254, verbose_name='Email')),
                ('event_booking', models.ManyToManyField(blank=True, related_name='booking_event', to=settings.AUTH_USER_MODEL)),
                ('event_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('event_tag', models.ManyToManyField(blank=True, null=True, related_name='tags_for_event', to='events.Tag')),
                ('event_venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.venue')),
            ],
        ),
    ]
