# Generated by Django 3.2.11 on 2022-10-05 20:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_capacitety',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
