# Generated by Django 3.2.11 on 2022-10-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20221007_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_image',
            field=models.ImageField(blank=True, default='static/image/user.png', upload_to='images/', verbose_name='Image'),
        ),
    ]
