# Generated by Django 3.2.11 on 2022-10-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_student_student_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_email',
        ),
        migrations.AlterField(
            model_name='student',
            name='student_image',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Image'),
        ),
    ]
